version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend-network

  clientapi:
    build:
      context: .
      dockerfile: ./Client/src/Client.API/Dockerfile
    image: clientapi
    container_name: clientapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ClientDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "5001:80"
    networks:
      - backend-network

  accountapi:
    build:
      context: .
      dockerfile: ./Account/src/Account.API/Dockerfile
    image: accountapi
    container_name: accountapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AccountDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "5002:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge